Move to latest go version 1.18
open-cluster-management-io/governance-policy-status-sync pull request #28
Opened 2022-06-14 20:13 UTC by gparvin

Refs:
 - https://github.com/stolostron/backlog/issues/22476

Signed-off-by: Gus Parvin <gparvin@redhat.com>

2022-06-14 20:28 UTC, gparvin commented
/retest

2022-06-14 20:40 UTC, dhaiducek requested changes
The workflows also need to be updated to 1.18

2022-06-15 19:17 UTC, mprahl submitted a review, later dismissed

2022-06-15 19:18 UTC, dhaiducek commented
/hold the Actions are still running `1.17`.

2022-06-16 13:26 UTC, gparvin commented
/retest

2022-06-21 13:14 UTC, mprahl commented
Since the required tests have changed to 1.18 to enable this PR, it has blocked #29.

2022-06-21 17:08 UTC, gparvin commented
Actions are 1.18 now.
/unhold

2022-06-21 17:35 UTC, dhaiducek commented on build/common/config/.golangci.yml
> +      - prefix(open-cluster-management.io/config-policy-controller)
This doesn't match this repo. Is that intended?

2022-06-21 17:51 UTC, gparvin commented on build/common/config/.golangci.yml
> +      - prefix(open-cluster-management.io/config-policy-controller)
Good catch.  Will add a fix

2022-06-21 18:12 UTC, dhaiducek approved these changes

2022-06-21 18:19 UTC, merged